import type { ActiveMatch, MatchPlayer, MatchTeam } from "./types";

const defaultStats = () => ({
  minutesPlayed: 0,
  goals: 0,
  assists: 0,
  shotsOnTarget: 0,
  shotsOffTarget: 0,
  foulsCommitted: 0,
  foulsReceived: 0,
  yellowCards: 0,
  redCards: 0,
  blueCards: 0,
  saves: 0,
});

export const samplePlayersHome: MatchPlayer[] = [
  {
    id: "hp-1",
    name: "Diogo Costa",
    number: 1,
    position: "GR",
    isStarter: true,
    isOnPitch: true,
    stats: defaultStats(),
  },
  {
    id: "hp-2",
    name: "João Cancelo",
    number: 2,
    position: "DD",
    isStarter: true,
    isOnPitch: true,
    stats: defaultStats(),
  },
  {
    id: "hp-3",
    name: "Rúben Dias",
    number: 3,
    position: "DC",
    isStarter: true,
    isOnPitch: true,
    stats: defaultStats(),
  },
  {
    id: "hp-4",
    name: "António Silva",
    number: 4,
    position: "DC",
    isStarter: true,
    isOnPitch: true,
    stats: defaultStats(),
  },
  {
    id: "hp-5",
    name: "Nuno Mendes",
    number: 5,
    position: "DE",
    isStarter: true,
    isOnPitch: true,
    stats: defaultStats(),
  },
  {
    id: "hp-6",
    name: "João Palhinha",
    number: 6,
    position: "MDF",
    isStarter: true,
    isOnPitch: true,
    stats: defaultStats(),
  },
  {
    id: "hp-8",
    name: "Vitinha",
    number: 8,
    position: "MC",
    isStarter: true,
    isOnPitch: true,
    stats: defaultStats(),
  },
  {
    id: "hp-10",
    name: "Bernardo Silva",
    number: 10,
    position: "MO",
    isStarter: true,
    isOnPitch: true,
    stats: defaultStats(),
  },
  {
    id: "hp-7",
    name: "Cristiano Ronaldo",
    number: 7,
    position: "PL",
    isStarter: true,
    isOnPitch: true,
    stats: defaultStats(),
  },
  {
    id: "hp-11",
    name: "Rafael Leão",
    number: 11,
    position: "EXT",
    isStarter: true,
    isOnPitch: true,
    stats: defaultStats(),
  },
  {
    id: "hp-9",
    name: "Gonçalo Ramos",
    number: 9,
    position: "PL",
    isStarter: true,
    isOnPitch: true,
    stats: defaultStats(),
  },
  // Suplentes
  {
    id: "hp-12",
    name: "José Sá",
    number: 12,
    position: "GR",
    isStarter: false,
    isOnPitch: false,
    stats: defaultStats(),
  },
  {
    id: "hp-14",
    name: "Gonçalo Inácio",
    number: 14,
    position: "DC",
    isStarter: false,
    isOnPitch: false,
    stats: defaultStats(),
  },
  {
    id: "hp-16",
    name: "Matheus Nunes",
    number: 16,
    position: "MC",
    isStarter: false,
    isOnPitch: false,
    stats: defaultStats(),
  },
  {
    id: "hp-18",
    name: "Rúben Neves",
    number: 18,
    position: "MC",
    isStarter: false,
    isOnPitch: false,
    stats: defaultStats(),
  },
  {
    id: "hp-20",
    name: "Pedro Neto",
    number: 20,
    position: "EXT",
    isStarter: false,
    isOnPitch: false,
    stats: defaultStats(),
  },
  {
    id: "hp-21",
    name: "Francisco Conceição",
    number: 21,
    position: "EXT",
    isStarter: false,
    isOnPitch: false,
    stats: defaultStats(),
  },
  {
    id: "hp-23",
    name: "João Félix",
    number: 23,
    position: "MO",
    isStarter: false,
    isOnPitch: false,
    stats: defaultStats(),
  },
];

export const samplePlayersAway: MatchPlayer[] = [
  {
    id: "ap-1",
    name: "Manuel Neuer",
    number: 1,
    position: "GR",
    isStarter: true,
    isOnPitch: true,
    stats: defaultStats(),
  },
  {
    id: "ap-2",
    name: "Joshua Kimmich",
    number: 6,
    position: "DD",
    isStarter: true,
    isOnPitch: true,
    stats: defaultStats(),
  },
  {
    id: "ap-3",
    name: "Antonio Rüdiger",
    number: 2,
    position: "DC",
    isStarter: true,
    isOnPitch: true,
    stats: defaultStats(),
  },
  {
    id: "ap-4",
    name: "Jonathan Tah",
    number: 4,
    position: "DC",
    isStarter: true,
    isOnPitch: true,
    stats: defaultStats(),
  },
  {
    id: "ap-5",
    name: "Maximilian Mittelstädt",
    number: 18,
    position: "DE",
    isStarter: true,
    isOnPitch: true,
    stats: defaultStats(),
  },
  {
    id: "ap-6",
    name: "Toni Kroos",
    number: 8,
    position: "MC",
    isStarter: true,
    isOnPitch: true,
    stats: defaultStats(),
  },
  {
    id: "ap-8",
    name: "Robert Andrich",
    number: 23,
    position: "MDF",
    isStarter: true,
    isOnPitch: true,
    stats: defaultStats(),
  },
  {
    id: "ap-10",
    name: "Jamal Musiala",
    number: 10,
    position: "MO",
    isStarter: true,
    isOnPitch: true,
    stats: defaultStats(),
  },
  {
    id: "ap-11",
    name: "Florian Wirtz",
    number: 17,
    position: "MO",
    isStarter: true,
    isOnPitch: true,
    stats: defaultStats(),
  },
  {
    id: "ap-7",
    name: "Leroy Sané",
    number: 19,
    position: "EXT",
    isStarter: true,
    isOnPitch: true,
    stats: defaultStats(),
  },
  {
    id: "ap-9",
    name: "Kai Havertz",
    number: 7,
    position: "PL",
    isStarter: true,
    isOnPitch: true,
    stats: defaultStats(),
  },
  // Suplentes
  {
    id: "ap-12",
    name: "Marc-André ter Stegen",
    number: 22,
    position: "GR",
    isStarter: false,
    isOnPitch: false,
    stats: defaultStats(),
  },
  {
    id: "ap-14",
    name: "Nico Schlotterbeck",
    number: 15,
    position: "DC",
    isStarter: false,
    isOnPitch: false,
    stats: defaultStats(),
  },
  {
    id: "ap-16",
    name: "Pascal Groß",
    number: 5,
    position: "MC",
    isStarter: false,
    isOnPitch: false,
    stats: defaultStats(),
  },
  {
    id: "ap-20",
    name: "Niclas Füllkrug",
    number: 9,
    position: "PL",
    isStarter: false,
    isOnPitch: false,
    stats: defaultStats(),
  },
  {
    id: "ap-21",
    name: "Thomas Müller",
    number: 13,
    position: "MO",
    isStarter: false,
    isOnPitch: false,
    stats: defaultStats(),
  },
];

export const sampleHomeTeam: MatchTeam = {
  id: "team-nws-fc",
  name: "Nova Web FC",
  shortName: "NWS",
  echelon: "Seniores Masculinos",
  primaryColor: "#10b981", // Emerald
  secondaryColor: "#047857",
  logoText: "NWS",
  players: samplePlayersHome,
};

export const sampleAwayTeam: MatchTeam = {
  id: "team-sc-cascais",
  name: "Sporting Clube de Cascais",
  shortName: "SCC",
  echelon: "Seniores Masculinos",
  primaryColor: "#3b82f6", // Blue
  secondaryColor: "#1d4ed8",
  logoText: "SCC",
  players: samplePlayersAway,
};

export function createDefaultMatch(
  modality: "futebol11" | "futebol9" | "futebol7" | "futsal" = "futsal",
): ActiveMatch {
  const isFutsal = modality === "futsal";
  const isF7 = modality === "futebol7";
  const isF9 = modality === "futebol9";

  const startersCount = isFutsal ? 5 : isF7 ? 7 : isF9 ? 9 : 11;

  const homePlayers = samplePlayersHome.map((p, idx) => ({
    ...p,
    isStarter: idx < startersCount,
    isOnPitch: idx < startersCount,
    stats: defaultStats(),
  }));

  const awayPlayers = samplePlayersAway.map((p, idx) => ({
    ...p,
    isStarter: idx < startersCount,
    isOnPitch: idx < startersCount,
    stats: defaultStats(),
  }));

  return {
    id: `match-${Date.now()}`,
    title: isFutsal ? "Liga de Futsal NWS • Jornada 1" : "Campeonato Distrital • Jornada 1",
    competition: isFutsal ? "Liga NWS Futsal" : "Campeonato Regional",
    location: "Pavilhão / Estádio Municipal",
    modality,
    periodMinutes: isFutsal ? 20 : isF7 ? 25 : isF9 ? 35 : 45,
    homeTeam: { ...sampleHomeTeam, players: homePlayers },
    awayTeam: { ...sampleAwayTeam, players: awayPlayers },
    homeScore: 0,
    awayScore: 0,
    homeFoulsPeriod: 0,
    awayFoulsPeriod: 0,
    periodState: "nao_iniciado",
    currentPeriod: 1,
    elapsedSeconds: 0,
    totalElapsedSeconds: 0,
    isRunning: false,
    events: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };
}
