/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as PortefolioRouteImport } from './routes/portefolio'
import { Route as RestaurantesRouteImport } from './routes/restaurantes'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedArquivosRouteImport } from './routes/_authenticated/arquivos'
import { Route as AuthenticatedDefinicoesRouteImport } from './routes/_authenticated/definicoes'
import { Route as AuthenticatedEmailsRouteImport } from './routes/_authenticated/emails'
import { Route as AuthenticatedEquipaRouteImport } from './routes/_authenticated/equipa'
import { Route as AuthenticatedHubRouteImport } from './routes/_authenticated/hub'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedPedidosRouteImport } from './routes/_authenticated/pedidos'
import { Route as AuthenticatedPipelineRouteImport } from './routes/_authenticated/pipeline'
import { Route as AuthenticatedProjetosRouteImport } from './routes/_authenticated/projetos'
import { Route as AuthenticatedSegurancaRouteImport } from './routes/_authenticated/seguranca'
import { Route as AuthenticatedTarefasRouteImport } from './routes/_authenticated/tarefas'
import { Route as DeIndexRouteImport } from './routes/de.index'
import { Route as DeContactRouteImport } from './routes/de.contact'
import { Route as DePortfolioRouteImport } from './routes/de.portfolio'
import { Route as DeRestaurantsRouteImport } from './routes/de.restaurants'
import { Route as EnIndexRouteImport } from './routes/en.index'
import { Route as EnContactRouteImport } from './routes/en.contact'
import { Route as EnPortfolioRouteImport } from './routes/en.portfolio'
import { Route as EnRestaurantsRouteImport } from './routes/en.restaurants'
import { Route as EsIndexRouteImport } from './routes/es.index'
import { Route as EsContactRouteImport } from './routes/es.contact'
import { Route as EsPortfolioRouteImport } from './routes/es.portfolio'
import { Route as EsRestaurantesRouteImport } from './routes/es.restaurantes'
import { Route as FrIndexRouteImport } from './routes/fr.index'
import { Route as FrContactRouteImport } from './routes/fr.contact'
import { Route as FrPortfolioRouteImport } from './routes/fr.portfolio'
import { Route as FrRestaurantsRouteImport } from './routes/fr.restaurants'
import { Route as AuthenticatedNegociosIndexRouteImport } from './routes/_authenticated/negocios.index'
import { Route as AuthenticatedNegociosIdRouteImport } from './routes/_authenticated/negocios.$id'
import { Route as AuthenticatedProdutosMatchRouteImport } from './routes/_authenticated/produtos.match'
import { Route as AuthenticatedProdutosRestaurantesRouteImport } from './routes/_authenticated/produtos.restaurantes'
import { Route as AuthenticatedProdutosRestaurantesIndexRouteImport } from './routes/_authenticated/produtos.restaurantes.index'
import { Route as AuthenticatedProdutosRestaurantesDefinicoesRouteImport } from './routes/_authenticated/produtos.restaurantes.definicoes'
import { Route as AuthenticatedProdutosRestaurantesEquipaRouteImport } from './routes/_authenticated/produtos.restaurantes.equipa'
import { Route as AuthenticatedProdutosRestaurantesMenuRouteImport } from './routes/_authenticated/produtos.restaurantes.menu'
import { Route as AuthenticatedProdutosRestaurantesMesasRouteImport } from './routes/_authenticated/produtos.restaurantes.mesas'
import { Route as AuthenticatedProdutosRestaurantesPedidosRouteImport } from './routes/_authenticated/produtos.restaurantes.pedidos'
import { Route as AuthenticatedProdutosRestaurantesReservasRouteImport } from './routes/_authenticated/produtos.restaurantes.reservas'
import { Route as AuthenticatedProdutosRestaurantesPedirMesaRouteImport } from './routes/_authenticated/produtos.restaurantes.pedir.$mesa'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const PortefolioRoute = PortefolioRouteImport.update({
  id: '/portefolio',
  path: '/portefolio',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantesRoute = RestaurantesRouteImport.update({
  id: '/restaurantes',
  path: '/restaurantes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArquivosRoute = AuthenticatedArquivosRouteImport.update({
  id: '/arquivos',
  path: '/arquivos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDefinicoesRoute = AuthenticatedDefinicoesRouteImport.update({
  id: '/definicoes',
  path: '/definicoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmailsRoute = AuthenticatedEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEquipaRoute = AuthenticatedEquipaRouteImport.update({
  id: '/equipa',
  path: '/equipa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHubRoute = AuthenticatedHubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPedidosRoute = AuthenticatedPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPipelineRoute = AuthenticatedPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjetosRoute = AuthenticatedProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSegurancaRoute = AuthenticatedSegurancaRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTarefasRoute = AuthenticatedTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DeIndexRoute = DeIndexRouteImport.update({
  id: '/de/',
  path: '/de/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeContactRoute = DeContactRouteImport.update({
  id: '/de/contact',
  path: '/de/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DePortfolioRoute = DePortfolioRouteImport.update({
  id: '/de/portfolio',
  path: '/de/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const DeRestaurantsRoute = DeRestaurantsRouteImport.update({
  id: '/de/restaurants',
  path: '/de/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnContactRoute = EnContactRouteImport.update({
  id: '/en/contact',
  path: '/en/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EnPortfolioRoute = EnPortfolioRouteImport.update({
  id: '/en/portfolio',
  path: '/en/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRestaurantsRoute = EnRestaurantsRouteImport.update({
  id: '/en/restaurants',
  path: '/en/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const EsIndexRoute = EsIndexRouteImport.update({
  id: '/es/',
  path: '/es/',
  getParentRoute: () => rootRouteImport,
} as any)
const EsContactRoute = EsContactRouteImport.update({
  id: '/es/contact',
  path: '/es/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EsPortfolioRoute = EsPortfolioRouteImport.update({
  id: '/es/portfolio',
  path: '/es/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const EsRestaurantesRoute = EsRestaurantesRouteImport.update({
  id: '/es/restaurantes',
  path: '/es/restaurantes',
  getParentRoute: () => rootRouteImport,
} as any)
const FrIndexRoute = FrIndexRouteImport.update({
  id: '/fr/',
  path: '/fr/',
  getParentRoute: () => rootRouteImport,
} as any)
const FrContactRoute = FrContactRouteImport.update({
  id: '/fr/contact',
  path: '/fr/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FrPortfolioRoute = FrPortfolioRouteImport.update({
  id: '/fr/portfolio',
  path: '/fr/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const FrRestaurantsRoute = FrRestaurantsRouteImport.update({
  id: '/fr/restaurants',
  path: '/fr/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNegociosIndexRoute =
  AuthenticatedNegociosIndexRouteImport.update({
    id: '/negocios/',
    path: '/negocios/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNegociosIdRoute = AuthenticatedNegociosIdRouteImport.update({
  id: '/negocios/$id',
  path: '/negocios/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProdutosMatchRoute =
  AuthenticatedProdutosMatchRouteImport.update({
    id: '/produtos/match',
    path: '/produtos/match',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProdutosRestaurantesRoute =
  AuthenticatedProdutosRestaurantesRouteImport.update({
    id: '/produtos/restaurantes',
    path: '/produtos/restaurantes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProdutosRestaurantesIndexRoute =
  AuthenticatedProdutosRestaurantesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProdutosRestaurantesRoute,
  } as any)
const AuthenticatedProdutosRestaurantesDefinicoesRoute =
  AuthenticatedProdutosRestaurantesDefinicoesRouteImport.update({
    id: '/definicoes',
    path: '/definicoes',
    getParentRoute: () => AuthenticatedProdutosRestaurantesRoute,
  } as any)
const AuthenticatedProdutosRestaurantesEquipaRoute =
  AuthenticatedProdutosRestaurantesEquipaRouteImport.update({
    id: '/equipa',
    path: '/equipa',
    getParentRoute: () => AuthenticatedProdutosRestaurantesRoute,
  } as any)
const AuthenticatedProdutosRestaurantesMenuRoute =
  AuthenticatedProdutosRestaurantesMenuRouteImport.update({
    id: '/menu',
    path: '/menu',
    getParentRoute: () => AuthenticatedProdutosRestaurantesRoute,
  } as any)
const AuthenticatedProdutosRestaurantesMesasRoute =
  AuthenticatedProdutosRestaurantesMesasRouteImport.update({
    id: '/mesas',
    path: '/mesas',
    getParentRoute: () => AuthenticatedProdutosRestaurantesRoute,
  } as any)
const AuthenticatedProdutosRestaurantesPedidosRoute =
  AuthenticatedProdutosRestaurantesPedidosRouteImport.update({
    id: '/pedidos',
    path: '/pedidos',
    getParentRoute: () => AuthenticatedProdutosRestaurantesRoute,
  } as any)
const AuthenticatedProdutosRestaurantesReservasRoute =
  AuthenticatedProdutosRestaurantesReservasRouteImport.update({
    id: '/reservas',
    path: '/reservas',
    getParentRoute: () => AuthenticatedProdutosRestaurantesRoute,
  } as any)
const AuthenticatedProdutosRestaurantesPedirMesaRoute =
  AuthenticatedProdutosRestaurantesPedirMesaRouteImport.update({
    id: '/pedir/$mesa',
    path: '/pedir/$mesa',
    getParentRoute: () => AuthenticatedProdutosRestaurantesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contacto': typeof ContactoRoute
  '/portefolio': typeof PortefolioRoute
  '/restaurantes': typeof RestaurantesRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/arquivos': typeof AuthenticatedArquivosRoute
  '/definicoes': typeof AuthenticatedDefinicoesRoute
  '/emails': typeof AuthenticatedEmailsRoute
  '/equipa': typeof AuthenticatedEquipaRoute
  '/hub': typeof AuthenticatedHubRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/pedidos': typeof AuthenticatedPedidosRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/projetos': typeof AuthenticatedProjetosRoute
  '/seguranca': typeof AuthenticatedSegurancaRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/de/contact': typeof DeContactRoute
  '/de/portfolio': typeof DePortfolioRoute
  '/de/restaurants': typeof DeRestaurantsRoute
  '/en/contact': typeof EnContactRoute
  '/en/portfolio': typeof EnPortfolioRoute
  '/en/restaurants': typeof EnRestaurantsRoute
  '/es/contact': typeof EsContactRoute
  '/es/portfolio': typeof EsPortfolioRoute
  '/es/restaurantes': typeof EsRestaurantesRoute
  '/fr/contact': typeof FrContactRoute
  '/fr/portfolio': typeof FrPortfolioRoute
  '/fr/restaurants': typeof FrRestaurantsRoute
  '/de/': typeof DeIndexRoute
  '/en/': typeof EnIndexRoute
  '/es/': typeof EsIndexRoute
  '/fr/': typeof FrIndexRoute
  '/negocios/$id': typeof AuthenticatedNegociosIdRoute
  '/produtos/match': typeof AuthenticatedProdutosMatchRoute
  '/produtos/restaurantes': typeof AuthenticatedProdutosRestaurantesRouteWithChildren
  '/negocios/': typeof AuthenticatedNegociosIndexRoute
  '/produtos/restaurantes/definicoes': typeof AuthenticatedProdutosRestaurantesDefinicoesRoute
  '/produtos/restaurantes/equipa': typeof AuthenticatedProdutosRestaurantesEquipaRoute
  '/produtos/restaurantes/menu': typeof AuthenticatedProdutosRestaurantesMenuRoute
  '/produtos/restaurantes/mesas': typeof AuthenticatedProdutosRestaurantesMesasRoute
  '/produtos/restaurantes/pedidos': typeof AuthenticatedProdutosRestaurantesPedidosRoute
  '/produtos/restaurantes/reservas': typeof AuthenticatedProdutosRestaurantesReservasRoute
  '/produtos/restaurantes/': typeof AuthenticatedProdutosRestaurantesIndexRoute
  '/produtos/restaurantes/pedir/$mesa': typeof AuthenticatedProdutosRestaurantesPedirMesaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contacto': typeof ContactoRoute
  '/portefolio': typeof PortefolioRoute
  '/restaurantes': typeof RestaurantesRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/arquivos': typeof AuthenticatedArquivosRoute
  '/definicoes': typeof AuthenticatedDefinicoesRoute
  '/emails': typeof AuthenticatedEmailsRoute
  '/equipa': typeof AuthenticatedEquipaRoute
  '/hub': typeof AuthenticatedHubRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/pedidos': typeof AuthenticatedPedidosRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/projetos': typeof AuthenticatedProjetosRoute
  '/seguranca': typeof AuthenticatedSegurancaRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/de/contact': typeof DeContactRoute
  '/de/portfolio': typeof DePortfolioRoute
  '/de/restaurants': typeof DeRestaurantsRoute
  '/en/contact': typeof EnContactRoute
  '/en/portfolio': typeof EnPortfolioRoute
  '/en/restaurants': typeof EnRestaurantsRoute
  '/es/contact': typeof EsContactRoute
  '/es/portfolio': typeof EsPortfolioRoute
  '/es/restaurantes': typeof EsRestaurantesRoute
  '/fr/contact': typeof FrContactRoute
  '/fr/portfolio': typeof FrPortfolioRoute
  '/fr/restaurants': typeof FrRestaurantsRoute
  '/de': typeof DeIndexRoute
  '/en': typeof EnIndexRoute
  '/es': typeof EsIndexRoute
  '/fr': typeof FrIndexRoute
  '/negocios/$id': typeof AuthenticatedNegociosIdRoute
  '/produtos/match': typeof AuthenticatedProdutosMatchRoute
  '/negocios': typeof AuthenticatedNegociosIndexRoute
  '/produtos/restaurantes/definicoes': typeof AuthenticatedProdutosRestaurantesDefinicoesRoute
  '/produtos/restaurantes/equipa': typeof AuthenticatedProdutosRestaurantesEquipaRoute
  '/produtos/restaurantes/menu': typeof AuthenticatedProdutosRestaurantesMenuRoute
  '/produtos/restaurantes/mesas': typeof AuthenticatedProdutosRestaurantesMesasRoute
  '/produtos/restaurantes/pedidos': typeof AuthenticatedProdutosRestaurantesPedidosRoute
  '/produtos/restaurantes/reservas': typeof AuthenticatedProdutosRestaurantesReservasRoute
  '/produtos/restaurantes': typeof AuthenticatedProdutosRestaurantesIndexRoute
  '/produtos/restaurantes/pedir/$mesa': typeof AuthenticatedProdutosRestaurantesPedirMesaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contacto': typeof ContactoRoute
  '/portefolio': typeof PortefolioRoute
  '/restaurantes': typeof RestaurantesRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/arquivos': typeof AuthenticatedArquivosRoute
  '/_authenticated/definicoes': typeof AuthenticatedDefinicoesRoute
  '/_authenticated/emails': typeof AuthenticatedEmailsRoute
  '/_authenticated/equipa': typeof AuthenticatedEquipaRoute
  '/_authenticated/hub': typeof AuthenticatedHubRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/pedidos': typeof AuthenticatedPedidosRoute
  '/_authenticated/pipeline': typeof AuthenticatedPipelineRoute
  '/_authenticated/projetos': typeof AuthenticatedProjetosRoute
  '/_authenticated/seguranca': typeof AuthenticatedSegurancaRoute
  '/_authenticated/tarefas': typeof AuthenticatedTarefasRoute
  '/de/contact': typeof DeContactRoute
  '/de/portfolio': typeof DePortfolioRoute
  '/de/restaurants': typeof DeRestaurantsRoute
  '/en/contact': typeof EnContactRoute
  '/en/portfolio': typeof EnPortfolioRoute
  '/en/restaurants': typeof EnRestaurantsRoute
  '/es/contact': typeof EsContactRoute
  '/es/portfolio': typeof EsPortfolioRoute
  '/es/restaurantes': typeof EsRestaurantesRoute
  '/fr/contact': typeof FrContactRoute
  '/fr/portfolio': typeof FrPortfolioRoute
  '/fr/restaurants': typeof FrRestaurantsRoute
  '/de/': typeof DeIndexRoute
  '/en/': typeof EnIndexRoute
  '/es/': typeof EsIndexRoute
  '/fr/': typeof FrIndexRoute
  '/_authenticated/negocios/$id': typeof AuthenticatedNegociosIdRoute
  '/_authenticated/produtos/match': typeof AuthenticatedProdutosMatchRoute
  '/_authenticated/produtos/restaurantes': typeof AuthenticatedProdutosRestaurantesRouteWithChildren
  '/_authenticated/negocios/': typeof AuthenticatedNegociosIndexRoute
  '/_authenticated/produtos/restaurantes/definicoes': typeof AuthenticatedProdutosRestaurantesDefinicoesRoute
  '/_authenticated/produtos/restaurantes/equipa': typeof AuthenticatedProdutosRestaurantesEquipaRoute
  '/_authenticated/produtos/restaurantes/menu': typeof AuthenticatedProdutosRestaurantesMenuRoute
  '/_authenticated/produtos/restaurantes/mesas': typeof AuthenticatedProdutosRestaurantesMesasRoute
  '/_authenticated/produtos/restaurantes/pedidos': typeof AuthenticatedProdutosRestaurantesPedidosRoute
  '/_authenticated/produtos/restaurantes/reservas': typeof AuthenticatedProdutosRestaurantesReservasRoute
  '/_authenticated/produtos/restaurantes/': typeof AuthenticatedProdutosRestaurantesIndexRoute
  '/_authenticated/produtos/restaurantes/pedir/$mesa': typeof AuthenticatedProdutosRestaurantesPedirMesaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contacto'
    | '/portefolio'
    | '/restaurantes'
    | '/admin'
    | '/arquivos'
    | '/definicoes'
    | '/emails'
    | '/equipa'
    | '/hub'
    | '/painel'
    | '/pedidos'
    | '/pipeline'
    | '/projetos'
    | '/seguranca'
    | '/tarefas'
    | '/de/contact'
    | '/de/portfolio'
    | '/de/restaurants'
    | '/en/contact'
    | '/en/portfolio'
    | '/en/restaurants'
    | '/es/contact'
    | '/es/portfolio'
    | '/es/restaurantes'
    | '/fr/contact'
    | '/fr/portfolio'
    | '/fr/restaurants'
    | '/de/'
    | '/en/'
    | '/es/'
    | '/fr/'
    | '/negocios/$id'
    | '/produtos/match'
    | '/produtos/restaurantes'
    | '/negocios/'
    | '/produtos/restaurantes/definicoes'
    | '/produtos/restaurantes/equipa'
    | '/produtos/restaurantes/menu'
    | '/produtos/restaurantes/mesas'
    | '/produtos/restaurantes/pedidos'
    | '/produtos/restaurantes/reservas'
    | '/produtos/restaurantes/'
    | '/produtos/restaurantes/pedir/$mesa'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contacto'
    | '/portefolio'
    | '/restaurantes'
    | '/admin'
    | '/arquivos'
    | '/definicoes'
    | '/emails'
    | '/equipa'
    | '/hub'
    | '/painel'
    | '/pedidos'
    | '/pipeline'
    | '/projetos'
    | '/seguranca'
    | '/tarefas'
    | '/de/contact'
    | '/de/portfolio'
    | '/de/restaurants'
    | '/en/contact'
    | '/en/portfolio'
    | '/en/restaurants'
    | '/es/contact'
    | '/es/portfolio'
    | '/es/restaurantes'
    | '/fr/contact'
    | '/fr/portfolio'
    | '/fr/restaurants'
    | '/de'
    | '/en'
    | '/es'
    | '/fr'
    | '/negocios/$id'
    | '/produtos/match'
    | '/negocios'
    | '/produtos/restaurantes/definicoes'
    | '/produtos/restaurantes/equipa'
    | '/produtos/restaurantes/menu'
    | '/produtos/restaurantes/mesas'
    | '/produtos/restaurantes/pedidos'
    | '/produtos/restaurantes/reservas'
    | '/produtos/restaurantes'
    | '/produtos/restaurantes/pedir/$mesa'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/contacto'
    | '/portefolio'
    | '/restaurantes'
    | '/_authenticated/admin'
    | '/_authenticated/arquivos'
    | '/_authenticated/definicoes'
    | '/_authenticated/emails'
    | '/_authenticated/equipa'
    | '/_authenticated/hub'
    | '/_authenticated/painel'
    | '/_authenticated/pedidos'
    | '/_authenticated/pipeline'
    | '/_authenticated/projetos'
    | '/_authenticated/seguranca'
    | '/_authenticated/tarefas'
    | '/de/contact'
    | '/de/portfolio'
    | '/de/restaurants'
    | '/en/contact'
    | '/en/portfolio'
    | '/en/restaurants'
    | '/es/contact'
    | '/es/portfolio'
    | '/es/restaurantes'
    | '/fr/contact'
    | '/fr/portfolio'
    | '/fr/restaurants'
    | '/de/'
    | '/en/'
    | '/es/'
    | '/fr/'
    | '/_authenticated/negocios/$id'
    | '/_authenticated/produtos/match'
    | '/_authenticated/produtos/restaurantes'
    | '/_authenticated/negocios/'
    | '/_authenticated/produtos/restaurantes/definicoes'
    | '/_authenticated/produtos/restaurantes/equipa'
    | '/_authenticated/produtos/restaurantes/menu'
    | '/_authenticated/produtos/restaurantes/mesas'
    | '/_authenticated/produtos/restaurantes/pedidos'
    | '/_authenticated/produtos/restaurantes/reservas'
    | '/_authenticated/produtos/restaurantes/'
    | '/_authenticated/produtos/restaurantes/pedir/$mesa'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactoRoute: typeof ContactoRoute
  PortefolioRoute: typeof PortefolioRoute
  RestaurantesRoute: typeof RestaurantesRoute
  DeContactRoute: typeof DeContactRoute
  DePortfolioRoute: typeof DePortfolioRoute
  DeRestaurantsRoute: typeof DeRestaurantsRoute
  EnContactRoute: typeof EnContactRoute
  EnPortfolioRoute: typeof EnPortfolioRoute
  EnRestaurantsRoute: typeof EnRestaurantsRoute
  EsContactRoute: typeof EsContactRoute
  EsPortfolioRoute: typeof EsPortfolioRoute
  EsRestaurantesRoute: typeof EsRestaurantesRoute
  FrContactRoute: typeof FrContactRoute
  FrPortfolioRoute: typeof FrPortfolioRoute
  FrRestaurantsRoute: typeof FrRestaurantsRoute
  DeIndexRoute: typeof DeIndexRoute
  EnIndexRoute: typeof EnIndexRoute
  EsIndexRoute: typeof EsIndexRoute
  FrIndexRoute: typeof FrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portefolio': {
      id: '/portefolio'
      path: '/portefolio'
      fullPath: '/portefolio'
      preLoaderRoute: typeof PortefolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurantes': {
      id: '/restaurantes'
      path: '/restaurantes'
      fullPath: '/restaurantes'
      preLoaderRoute: typeof RestaurantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/arquivos': {
      id: '/_authenticated/arquivos'
      path: '/arquivos'
      fullPath: '/arquivos'
      preLoaderRoute: typeof AuthenticatedArquivosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/definicoes': {
      id: '/_authenticated/definicoes'
      path: '/definicoes'
      fullPath: '/definicoes'
      preLoaderRoute: typeof AuthenticatedDefinicoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/emails': {
      id: '/_authenticated/emails'
      path: '/emails'
      fullPath: '/emails'
      preLoaderRoute: typeof AuthenticatedEmailsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipa': {
      id: '/_authenticated/equipa'
      path: '/equipa'
      fullPath: '/equipa'
      preLoaderRoute: typeof AuthenticatedEquipaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hub': {
      id: '/_authenticated/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof AuthenticatedHubRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedidos': {
      id: '/_authenticated/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof AuthenticatedPedidosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pipeline': {
      id: '/_authenticated/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AuthenticatedPipelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projetos': {
      id: '/_authenticated/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof AuthenticatedProjetosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seguranca': {
      id: '/_authenticated/seguranca'
      path: '/seguranca'
      fullPath: '/seguranca'
      preLoaderRoute: typeof AuthenticatedSegurancaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tarefas': {
      id: '/_authenticated/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof AuthenticatedTarefasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/de/': {
      id: '/de/'
      path: '/de'
      fullPath: '/de/'
      preLoaderRoute: typeof DeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de/contact': {
      id: '/de/contact'
      path: '/de/contact'
      fullPath: '/de/contact'
      preLoaderRoute: typeof DeContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de/portfolio': {
      id: '/de/portfolio'
      path: '/de/portfolio'
      fullPath: '/de/portfolio'
      preLoaderRoute: typeof DePortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de/restaurants': {
      id: '/de/restaurants'
      path: '/de/restaurants'
      fullPath: '/de/restaurants'
      preLoaderRoute: typeof DeRestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/contact': {
      id: '/en/contact'
      path: '/en/contact'
      fullPath: '/en/contact'
      preLoaderRoute: typeof EnContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/portfolio': {
      id: '/en/portfolio'
      path: '/en/portfolio'
      fullPath: '/en/portfolio'
      preLoaderRoute: typeof EnPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/restaurants': {
      id: '/en/restaurants'
      path: '/en/restaurants'
      fullPath: '/en/restaurants'
      preLoaderRoute: typeof EnRestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/': {
      id: '/es/'
      path: '/es'
      fullPath: '/es/'
      preLoaderRoute: typeof EsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/contact': {
      id: '/es/contact'
      path: '/es/contact'
      fullPath: '/es/contact'
      preLoaderRoute: typeof EsContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/portfolio': {
      id: '/es/portfolio'
      path: '/es/portfolio'
      fullPath: '/es/portfolio'
      preLoaderRoute: typeof EsPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/restaurantes': {
      id: '/es/restaurantes'
      path: '/es/restaurantes'
      fullPath: '/es/restaurantes'
      preLoaderRoute: typeof EsRestaurantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/': {
      id: '/fr/'
      path: '/fr'
      fullPath: '/fr/'
      preLoaderRoute: typeof FrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/contact': {
      id: '/fr/contact'
      path: '/fr/contact'
      fullPath: '/fr/contact'
      preLoaderRoute: typeof FrContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/portfolio': {
      id: '/fr/portfolio'
      path: '/fr/portfolio'
      fullPath: '/fr/portfolio'
      preLoaderRoute: typeof FrPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/restaurants': {
      id: '/fr/restaurants'
      path: '/fr/restaurants'
      fullPath: '/fr/restaurants'
      preLoaderRoute: typeof FrRestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/negocios/': {
      id: '/_authenticated/negocios/'
      path: '/negocios'
      fullPath: '/negocios/'
      preLoaderRoute: typeof AuthenticatedNegociosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/negocios/$id': {
      id: '/_authenticated/negocios/$id'
      path: '/negocios/$id'
      fullPath: '/negocios/$id'
      preLoaderRoute: typeof AuthenticatedNegociosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtos/match': {
      id: '/_authenticated/produtos/match'
      path: '/produtos/match'
      fullPath: '/produtos/match'
      preLoaderRoute: typeof AuthenticatedProdutosMatchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtos/restaurantes': {
      id: '/_authenticated/produtos/restaurantes'
      path: '/produtos/restaurantes'
      fullPath: '/produtos/restaurantes'
      preLoaderRoute: typeof AuthenticatedProdutosRestaurantesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtos/restaurantes/': {
      id: '/_authenticated/produtos/restaurantes/'
      path: '/'
      fullPath: '/produtos/restaurantes/'
      preLoaderRoute: typeof AuthenticatedProdutosRestaurantesIndexRouteImport
      parentRoute: typeof AuthenticatedProdutosRestaurantesRoute
    }
    '/_authenticated/produtos/restaurantes/definicoes': {
      id: '/_authenticated/produtos/restaurantes/definicoes'
      path: '/definicoes'
      fullPath: '/produtos/restaurantes/definicoes'
      preLoaderRoute: typeof AuthenticatedProdutosRestaurantesDefinicoesRouteImport
      parentRoute: typeof AuthenticatedProdutosRestaurantesRoute
    }
    '/_authenticated/produtos/restaurantes/equipa': {
      id: '/_authenticated/produtos/restaurantes/equipa'
      path: '/equipa'
      fullPath: '/produtos/restaurantes/equipa'
      preLoaderRoute: typeof AuthenticatedProdutosRestaurantesEquipaRouteImport
      parentRoute: typeof AuthenticatedProdutosRestaurantesRoute
    }
    '/_authenticated/produtos/restaurantes/menu': {
      id: '/_authenticated/produtos/restaurantes/menu'
      path: '/menu'
      fullPath: '/produtos/restaurantes/menu'
      preLoaderRoute: typeof AuthenticatedProdutosRestaurantesMenuRouteImport
      parentRoute: typeof AuthenticatedProdutosRestaurantesRoute
    }
    '/_authenticated/produtos/restaurantes/mesas': {
      id: '/_authenticated/produtos/restaurantes/mesas'
      path: '/mesas'
      fullPath: '/produtos/restaurantes/mesas'
      preLoaderRoute: typeof AuthenticatedProdutosRestaurantesMesasRouteImport
      parentRoute: typeof AuthenticatedProdutosRestaurantesRoute
    }
    '/_authenticated/produtos/restaurantes/pedidos': {
      id: '/_authenticated/produtos/restaurantes/pedidos'
      path: '/pedidos'
      fullPath: '/produtos/restaurantes/pedidos'
      preLoaderRoute: typeof AuthenticatedProdutosRestaurantesPedidosRouteImport
      parentRoute: typeof AuthenticatedProdutosRestaurantesRoute
    }
    '/_authenticated/produtos/restaurantes/reservas': {
      id: '/_authenticated/produtos/restaurantes/reservas'
      path: '/reservas'
      fullPath: '/produtos/restaurantes/reservas'
      preLoaderRoute: typeof AuthenticatedProdutosRestaurantesReservasRouteImport
      parentRoute: typeof AuthenticatedProdutosRestaurantesRoute
    }
    '/_authenticated/produtos/restaurantes/pedir/$mesa': {
      id: '/_authenticated/produtos/restaurantes/pedir/$mesa'
      path: '/pedir/$mesa'
      fullPath: '/produtos/restaurantes/pedir/$mesa'
      preLoaderRoute: typeof AuthenticatedProdutosRestaurantesPedirMesaRouteImport
      parentRoute: typeof AuthenticatedProdutosRestaurantesRoute
    }
  }
}

interface AuthenticatedProdutosRestaurantesRouteChildren {
  AuthenticatedProdutosRestaurantesDefinicoesRoute: typeof AuthenticatedProdutosRestaurantesDefinicoesRoute
  AuthenticatedProdutosRestaurantesEquipaRoute: typeof AuthenticatedProdutosRestaurantesEquipaRoute
  AuthenticatedProdutosRestaurantesMenuRoute: typeof AuthenticatedProdutosRestaurantesMenuRoute
  AuthenticatedProdutosRestaurantesMesasRoute: typeof AuthenticatedProdutosRestaurantesMesasRoute
  AuthenticatedProdutosRestaurantesPedidosRoute: typeof AuthenticatedProdutosRestaurantesPedidosRoute
  AuthenticatedProdutosRestaurantesReservasRoute: typeof AuthenticatedProdutosRestaurantesReservasRoute
  AuthenticatedProdutosRestaurantesIndexRoute: typeof AuthenticatedProdutosRestaurantesIndexRoute
  AuthenticatedProdutosRestaurantesPedirMesaRoute: typeof AuthenticatedProdutosRestaurantesPedirMesaRoute
}

const AuthenticatedProdutosRestaurantesRouteChildren: AuthenticatedProdutosRestaurantesRouteChildren =
  {
    AuthenticatedProdutosRestaurantesDefinicoesRoute:
      AuthenticatedProdutosRestaurantesDefinicoesRoute,
    AuthenticatedProdutosRestaurantesEquipaRoute:
      AuthenticatedProdutosRestaurantesEquipaRoute,
    AuthenticatedProdutosRestaurantesMenuRoute:
      AuthenticatedProdutosRestaurantesMenuRoute,
    AuthenticatedProdutosRestaurantesMesasRoute:
      AuthenticatedProdutosRestaurantesMesasRoute,
    AuthenticatedProdutosRestaurantesPedidosRoute:
      AuthenticatedProdutosRestaurantesPedidosRoute,
    AuthenticatedProdutosRestaurantesReservasRoute:
      AuthenticatedProdutosRestaurantesReservasRoute,
    AuthenticatedProdutosRestaurantesIndexRoute:
      AuthenticatedProdutosRestaurantesIndexRoute,
    AuthenticatedProdutosRestaurantesPedirMesaRoute:
      AuthenticatedProdutosRestaurantesPedirMesaRoute,
  }

const AuthenticatedProdutosRestaurantesRouteWithChildren =
  AuthenticatedProdutosRestaurantesRoute._addFileChildren(
    AuthenticatedProdutosRestaurantesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedArquivosRoute: typeof AuthenticatedArquivosRoute
  AuthenticatedDefinicoesRoute: typeof AuthenticatedDefinicoesRoute
  AuthenticatedEmailsRoute: typeof AuthenticatedEmailsRoute
  AuthenticatedEquipaRoute: typeof AuthenticatedEquipaRoute
  AuthenticatedHubRoute: typeof AuthenticatedHubRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedPedidosRoute: typeof AuthenticatedPedidosRoute
  AuthenticatedPipelineRoute: typeof AuthenticatedPipelineRoute
  AuthenticatedProjetosRoute: typeof AuthenticatedProjetosRoute
  AuthenticatedSegurancaRoute: typeof AuthenticatedSegurancaRoute
  AuthenticatedTarefasRoute: typeof AuthenticatedTarefasRoute
  AuthenticatedNegociosIdRoute: typeof AuthenticatedNegociosIdRoute
  AuthenticatedProdutosMatchRoute: typeof AuthenticatedProdutosMatchRoute
  AuthenticatedProdutosRestaurantesRoute: typeof AuthenticatedProdutosRestaurantesRouteWithChildren
  AuthenticatedNegociosIndexRoute: typeof AuthenticatedNegociosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedArquivosRoute: AuthenticatedArquivosRoute,
  AuthenticatedDefinicoesRoute: AuthenticatedDefinicoesRoute,
  AuthenticatedEmailsRoute: AuthenticatedEmailsRoute,
  AuthenticatedEquipaRoute: AuthenticatedEquipaRoute,
  AuthenticatedHubRoute: AuthenticatedHubRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedPedidosRoute: AuthenticatedPedidosRoute,
  AuthenticatedPipelineRoute: AuthenticatedPipelineRoute,
  AuthenticatedProjetosRoute: AuthenticatedProjetosRoute,
  AuthenticatedSegurancaRoute: AuthenticatedSegurancaRoute,
  AuthenticatedTarefasRoute: AuthenticatedTarefasRoute,
  AuthenticatedNegociosIdRoute: AuthenticatedNegociosIdRoute,
  AuthenticatedProdutosMatchRoute: AuthenticatedProdutosMatchRoute,
  AuthenticatedProdutosRestaurantesRoute:
    AuthenticatedProdutosRestaurantesRouteWithChildren,
  AuthenticatedNegociosIndexRoute: AuthenticatedNegociosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactoRoute: ContactoRoute,
  PortefolioRoute: PortefolioRoute,
  RestaurantesRoute: RestaurantesRoute,
  DeContactRoute: DeContactRoute,
  DePortfolioRoute: DePortfolioRoute,
  DeRestaurantsRoute: DeRestaurantsRoute,
  EnContactRoute: EnContactRoute,
  EnPortfolioRoute: EnPortfolioRoute,
  EnRestaurantsRoute: EnRestaurantsRoute,
  EsContactRoute: EsContactRoute,
  EsPortfolioRoute: EsPortfolioRoute,
  EsRestaurantesRoute: EsRestaurantesRoute,
  FrContactRoute: FrContactRoute,
  FrPortfolioRoute: FrPortfolioRoute,
  FrRestaurantsRoute: FrRestaurantsRoute,
  DeIndexRoute: DeIndexRoute,
  EnIndexRoute: EnIndexRoute,
  EsIndexRoute: EsIndexRoute,
  FrIndexRoute: FrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
