/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as PortefolioRouteImport } from './routes/portefolio'
import { Route as RestaurantesRouteImport } from './routes/restaurantes'
import { Route as AuthenticatedArquivosRouteImport } from './routes/_authenticated/arquivos'
import { Route as AuthenticatedDefinicoesRouteImport } from './routes/_authenticated/definicoes'
import { Route as AuthenticatedEmailsRouteImport } from './routes/_authenticated/emails'
import { Route as AuthenticatedEquipaRouteImport } from './routes/_authenticated/equipa'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedPedidosRouteImport } from './routes/_authenticated/pedidos'
import { Route as AuthenticatedPipelineRouteImport } from './routes/_authenticated/pipeline'
import { Route as AuthenticatedProjetosRouteImport } from './routes/_authenticated/projetos'
import { Route as AuthenticatedTarefasRouteImport } from './routes/_authenticated/tarefas'
import { Route as DeIndexRouteImport } from './routes/de.index'
import { Route as DeContactRouteImport } from './routes/de.contact'
import { Route as DePortfolioRouteImport } from './routes/de.portfolio'
import { Route as DeRestaurantsRouteImport } from './routes/de.restaurants'
import { Route as EnIndexRouteImport } from './routes/en.index'
import { Route as EnContactRouteImport } from './routes/en.contact'
import { Route as EnPortfolioRouteImport } from './routes/en.portfolio'
import { Route as EnRestaurantsRouteImport } from './routes/en.restaurants'
import { Route as EsIndexRouteImport } from './routes/es.index'
import { Route as EsContactRouteImport } from './routes/es.contact'
import { Route as EsPortfolioRouteImport } from './routes/es.portfolio'
import { Route as EsRestaurantesRouteImport } from './routes/es.restaurantes'
import { Route as FrIndexRouteImport } from './routes/fr.index'
import { Route as FrContactRouteImport } from './routes/fr.contact'
import { Route as FrPortfolioRouteImport } from './routes/fr.portfolio'
import { Route as FrRestaurantsRouteImport } from './routes/fr.restaurants'
import { Route as RestaurantesDemonstracaoRouteImport } from './routes/restaurantes_.demonstracao'
import { Route as AuthenticatedNegociosIndexRouteImport } from './routes/_authenticated/negocios.index'
import { Route as AuthenticatedNegociosIdRouteImport } from './routes/_authenticated/negocios.$id'
import { Route as DeRestaurantsDemoRouteImport } from './routes/de.restaurants_.demo'
import { Route as EnRestaurantsDemoRouteImport } from './routes/en.restaurants_.demo'
import { Route as EsRestaurantesDemoRouteImport } from './routes/es.restaurantes_.demo'
import { Route as FrRestaurantsDemoRouteImport } from './routes/fr.restaurants_.demo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const PortefolioRoute = PortefolioRouteImport.update({
  id: '/portefolio',
  path: '/portefolio',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantesRoute = RestaurantesRouteImport.update({
  id: '/restaurantes',
  path: '/restaurantes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedArquivosRoute = AuthenticatedArquivosRouteImport.update({
  id: '/arquivos',
  path: '/arquivos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDefinicoesRoute = AuthenticatedDefinicoesRouteImport.update({
  id: '/definicoes',
  path: '/definicoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmailsRoute = AuthenticatedEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEquipaRoute = AuthenticatedEquipaRouteImport.update({
  id: '/equipa',
  path: '/equipa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPedidosRoute = AuthenticatedPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPipelineRoute = AuthenticatedPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjetosRoute = AuthenticatedProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTarefasRoute = AuthenticatedTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DeIndexRoute = DeIndexRouteImport.update({
  id: '/de/',
  path: '/de/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeContactRoute = DeContactRouteImport.update({
  id: '/de/contact',
  path: '/de/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DePortfolioRoute = DePortfolioRouteImport.update({
  id: '/de/portfolio',
  path: '/de/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const DeRestaurantsRoute = DeRestaurantsRouteImport.update({
  id: '/de/restaurants',
  path: '/de/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnContactRoute = EnContactRouteImport.update({
  id: '/en/contact',
  path: '/en/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EnPortfolioRoute = EnPortfolioRouteImport.update({
  id: '/en/portfolio',
  path: '/en/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRestaurantsRoute = EnRestaurantsRouteImport.update({
  id: '/en/restaurants',
  path: '/en/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const EsIndexRoute = EsIndexRouteImport.update({
  id: '/es/',
  path: '/es/',
  getParentRoute: () => rootRouteImport,
} as any)
const EsContactRoute = EsContactRouteImport.update({
  id: '/es/contact',
  path: '/es/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EsPortfolioRoute = EsPortfolioRouteImport.update({
  id: '/es/portfolio',
  path: '/es/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const EsRestaurantesRoute = EsRestaurantesRouteImport.update({
  id: '/es/restaurantes',
  path: '/es/restaurantes',
  getParentRoute: () => rootRouteImport,
} as any)
const FrIndexRoute = FrIndexRouteImport.update({
  id: '/fr/',
  path: '/fr/',
  getParentRoute: () => rootRouteImport,
} as any)
const FrContactRoute = FrContactRouteImport.update({
  id: '/fr/contact',
  path: '/fr/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FrPortfolioRoute = FrPortfolioRouteImport.update({
  id: '/fr/portfolio',
  path: '/fr/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const FrRestaurantsRoute = FrRestaurantsRouteImport.update({
  id: '/fr/restaurants',
  path: '/fr/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantesDemonstracaoRoute =
  RestaurantesDemonstracaoRouteImport.update({
    id: '/restaurantes_/demonstracao',
    path: '/restaurantes/demonstracao',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedNegociosIndexRoute =
  AuthenticatedNegociosIndexRouteImport.update({
    id: '/negocios/',
    path: '/negocios/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNegociosIdRoute = AuthenticatedNegociosIdRouteImport.update({
  id: '/negocios/$id',
  path: '/negocios/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DeRestaurantsDemoRoute = DeRestaurantsDemoRouteImport.update({
  id: '/de/restaurants_/demo',
  path: '/de/restaurants/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRestaurantsDemoRoute = EnRestaurantsDemoRouteImport.update({
  id: '/en/restaurants_/demo',
  path: '/en/restaurants/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const EsRestaurantesDemoRoute = EsRestaurantesDemoRouteImport.update({
  id: '/es/restaurantes_/demo',
  path: '/es/restaurantes/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const FrRestaurantsDemoRoute = FrRestaurantsDemoRouteImport.update({
  id: '/fr/restaurants_/demo',
  path: '/fr/restaurants/demo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contacto': typeof ContactoRoute
  '/portefolio': typeof PortefolioRoute
  '/restaurantes': typeof RestaurantesRoute
  '/arquivos': typeof AuthenticatedArquivosRoute
  '/definicoes': typeof AuthenticatedDefinicoesRoute
  '/emails': typeof AuthenticatedEmailsRoute
  '/equipa': typeof AuthenticatedEquipaRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/pedidos': typeof AuthenticatedPedidosRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/projetos': typeof AuthenticatedProjetosRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/de/contact': typeof DeContactRoute
  '/de/portfolio': typeof DePortfolioRoute
  '/de/restaurants': typeof DeRestaurantsRoute
  '/en/contact': typeof EnContactRoute
  '/en/portfolio': typeof EnPortfolioRoute
  '/en/restaurants': typeof EnRestaurantsRoute
  '/es/contact': typeof EsContactRoute
  '/es/portfolio': typeof EsPortfolioRoute
  '/es/restaurantes': typeof EsRestaurantesRoute
  '/fr/contact': typeof FrContactRoute
  '/fr/portfolio': typeof FrPortfolioRoute
  '/fr/restaurants': typeof FrRestaurantsRoute
  '/restaurantes/demonstracao': typeof RestaurantesDemonstracaoRoute
  '/de/': typeof DeIndexRoute
  '/en/': typeof EnIndexRoute
  '/es/': typeof EsIndexRoute
  '/fr/': typeof FrIndexRoute
  '/negocios/$id': typeof AuthenticatedNegociosIdRoute
  '/de/restaurants/demo': typeof DeRestaurantsDemoRoute
  '/en/restaurants/demo': typeof EnRestaurantsDemoRoute
  '/es/restaurantes/demo': typeof EsRestaurantesDemoRoute
  '/fr/restaurants/demo': typeof FrRestaurantsDemoRoute
  '/negocios/': typeof AuthenticatedNegociosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contacto': typeof ContactoRoute
  '/portefolio': typeof PortefolioRoute
  '/restaurantes': typeof RestaurantesRoute
  '/arquivos': typeof AuthenticatedArquivosRoute
  '/definicoes': typeof AuthenticatedDefinicoesRoute
  '/emails': typeof AuthenticatedEmailsRoute
  '/equipa': typeof AuthenticatedEquipaRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/pedidos': typeof AuthenticatedPedidosRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/projetos': typeof AuthenticatedProjetosRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/de/contact': typeof DeContactRoute
  '/de/portfolio': typeof DePortfolioRoute
  '/de/restaurants': typeof DeRestaurantsRoute
  '/en/contact': typeof EnContactRoute
  '/en/portfolio': typeof EnPortfolioRoute
  '/en/restaurants': typeof EnRestaurantsRoute
  '/es/contact': typeof EsContactRoute
  '/es/portfolio': typeof EsPortfolioRoute
  '/es/restaurantes': typeof EsRestaurantesRoute
  '/fr/contact': typeof FrContactRoute
  '/fr/portfolio': typeof FrPortfolioRoute
  '/fr/restaurants': typeof FrRestaurantsRoute
  '/restaurantes/demonstracao': typeof RestaurantesDemonstracaoRoute
  '/de': typeof DeIndexRoute
  '/en': typeof EnIndexRoute
  '/es': typeof EsIndexRoute
  '/fr': typeof FrIndexRoute
  '/negocios/$id': typeof AuthenticatedNegociosIdRoute
  '/de/restaurants/demo': typeof DeRestaurantsDemoRoute
  '/en/restaurants/demo': typeof EnRestaurantsDemoRoute
  '/es/restaurantes/demo': typeof EsRestaurantesDemoRoute
  '/fr/restaurants/demo': typeof FrRestaurantsDemoRoute
  '/negocios': typeof AuthenticatedNegociosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contacto': typeof ContactoRoute
  '/portefolio': typeof PortefolioRoute
  '/restaurantes': typeof RestaurantesRoute
  '/_authenticated/arquivos': typeof AuthenticatedArquivosRoute
  '/_authenticated/definicoes': typeof AuthenticatedDefinicoesRoute
  '/_authenticated/emails': typeof AuthenticatedEmailsRoute
  '/_authenticated/equipa': typeof AuthenticatedEquipaRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/pedidos': typeof AuthenticatedPedidosRoute
  '/_authenticated/pipeline': typeof AuthenticatedPipelineRoute
  '/_authenticated/projetos': typeof AuthenticatedProjetosRoute
  '/_authenticated/tarefas': typeof AuthenticatedTarefasRoute
  '/de/contact': typeof DeContactRoute
  '/de/portfolio': typeof DePortfolioRoute
  '/de/restaurants': typeof DeRestaurantsRoute
  '/en/contact': typeof EnContactRoute
  '/en/portfolio': typeof EnPortfolioRoute
  '/en/restaurants': typeof EnRestaurantsRoute
  '/es/contact': typeof EsContactRoute
  '/es/portfolio': typeof EsPortfolioRoute
  '/es/restaurantes': typeof EsRestaurantesRoute
  '/fr/contact': typeof FrContactRoute
  '/fr/portfolio': typeof FrPortfolioRoute
  '/fr/restaurants': typeof FrRestaurantsRoute
  '/restaurantes_/demonstracao': typeof RestaurantesDemonstracaoRoute
  '/de/': typeof DeIndexRoute
  '/en/': typeof EnIndexRoute
  '/es/': typeof EsIndexRoute
  '/fr/': typeof FrIndexRoute
  '/_authenticated/negocios/$id': typeof AuthenticatedNegociosIdRoute
  '/de/restaurants_/demo': typeof DeRestaurantsDemoRoute
  '/en/restaurants_/demo': typeof EnRestaurantsDemoRoute
  '/es/restaurantes_/demo': typeof EsRestaurantesDemoRoute
  '/fr/restaurants_/demo': typeof FrRestaurantsDemoRoute
  '/_authenticated/negocios/': typeof AuthenticatedNegociosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contacto'
    | '/portefolio'
    | '/restaurantes'
    | '/arquivos'
    | '/definicoes'
    | '/emails'
    | '/equipa'
    | '/painel'
    | '/pedidos'
    | '/pipeline'
    | '/projetos'
    | '/tarefas'
    | '/de/contact'
    | '/de/portfolio'
    | '/de/restaurants'
    | '/en/contact'
    | '/en/portfolio'
    | '/en/restaurants'
    | '/es/contact'
    | '/es/portfolio'
    | '/es/restaurantes'
    | '/fr/contact'
    | '/fr/portfolio'
    | '/fr/restaurants'
    | '/restaurantes/demonstracao'
    | '/de/'
    | '/en/'
    | '/es/'
    | '/fr/'
    | '/negocios/$id'
    | '/de/restaurants/demo'
    | '/en/restaurants/demo'
    | '/es/restaurantes/demo'
    | '/fr/restaurants/demo'
    | '/negocios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contacto'
    | '/portefolio'
    | '/restaurantes'
    | '/arquivos'
    | '/definicoes'
    | '/emails'
    | '/equipa'
    | '/painel'
    | '/pedidos'
    | '/pipeline'
    | '/projetos'
    | '/tarefas'
    | '/de/contact'
    | '/de/portfolio'
    | '/de/restaurants'
    | '/en/contact'
    | '/en/portfolio'
    | '/en/restaurants'
    | '/es/contact'
    | '/es/portfolio'
    | '/es/restaurantes'
    | '/fr/contact'
    | '/fr/portfolio'
    | '/fr/restaurants'
    | '/restaurantes/demonstracao'
    | '/de'
    | '/en'
    | '/es'
    | '/fr'
    | '/negocios/$id'
    | '/de/restaurants/demo'
    | '/en/restaurants/demo'
    | '/es/restaurantes/demo'
    | '/fr/restaurants/demo'
    | '/negocios'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/contacto'
    | '/portefolio'
    | '/restaurantes'
    | '/_authenticated/arquivos'
    | '/_authenticated/definicoes'
    | '/_authenticated/emails'
    | '/_authenticated/equipa'
    | '/_authenticated/painel'
    | '/_authenticated/pedidos'
    | '/_authenticated/pipeline'
    | '/_authenticated/projetos'
    | '/_authenticated/tarefas'
    | '/de/contact'
    | '/de/portfolio'
    | '/de/restaurants'
    | '/en/contact'
    | '/en/portfolio'
    | '/en/restaurants'
    | '/es/contact'
    | '/es/portfolio'
    | '/es/restaurantes'
    | '/fr/contact'
    | '/fr/portfolio'
    | '/fr/restaurants'
    | '/restaurantes_/demonstracao'
    | '/de/'
    | '/en/'
    | '/es/'
    | '/fr/'
    | '/_authenticated/negocios/$id'
    | '/de/restaurants_/demo'
    | '/en/restaurants_/demo'
    | '/es/restaurantes_/demo'
    | '/fr/restaurants_/demo'
    | '/_authenticated/negocios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactoRoute: typeof ContactoRoute
  PortefolioRoute: typeof PortefolioRoute
  RestaurantesRoute: typeof RestaurantesRoute
  DeContactRoute: typeof DeContactRoute
  DePortfolioRoute: typeof DePortfolioRoute
  DeRestaurantsRoute: typeof DeRestaurantsRoute
  EnContactRoute: typeof EnContactRoute
  EnPortfolioRoute: typeof EnPortfolioRoute
  EnRestaurantsRoute: typeof EnRestaurantsRoute
  EsContactRoute: typeof EsContactRoute
  EsPortfolioRoute: typeof EsPortfolioRoute
  EsRestaurantesRoute: typeof EsRestaurantesRoute
  FrContactRoute: typeof FrContactRoute
  FrPortfolioRoute: typeof FrPortfolioRoute
  FrRestaurantsRoute: typeof FrRestaurantsRoute
  RestaurantesDemonstracaoRoute: typeof RestaurantesDemonstracaoRoute
  DeIndexRoute: typeof DeIndexRoute
  EnIndexRoute: typeof EnIndexRoute
  EsIndexRoute: typeof EsIndexRoute
  FrIndexRoute: typeof FrIndexRoute
  DeRestaurantsDemoRoute: typeof DeRestaurantsDemoRoute
  EnRestaurantsDemoRoute: typeof EnRestaurantsDemoRoute
  EsRestaurantesDemoRoute: typeof EsRestaurantesDemoRoute
  FrRestaurantsDemoRoute: typeof FrRestaurantsDemoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portefolio': {
      id: '/portefolio'
      path: '/portefolio'
      fullPath: '/portefolio'
      preLoaderRoute: typeof PortefolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurantes': {
      id: '/restaurantes'
      path: '/restaurantes'
      fullPath: '/restaurantes'
      preLoaderRoute: typeof RestaurantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/arquivos': {
      id: '/_authenticated/arquivos'
      path: '/arquivos'
      fullPath: '/arquivos'
      preLoaderRoute: typeof AuthenticatedArquivosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/definicoes': {
      id: '/_authenticated/definicoes'
      path: '/definicoes'
      fullPath: '/definicoes'
      preLoaderRoute: typeof AuthenticatedDefinicoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/emails': {
      id: '/_authenticated/emails'
      path: '/emails'
      fullPath: '/emails'
      preLoaderRoute: typeof AuthenticatedEmailsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipa': {
      id: '/_authenticated/equipa'
      path: '/equipa'
      fullPath: '/equipa'
      preLoaderRoute: typeof AuthenticatedEquipaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedidos': {
      id: '/_authenticated/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof AuthenticatedPedidosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pipeline': {
      id: '/_authenticated/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AuthenticatedPipelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projetos': {
      id: '/_authenticated/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof AuthenticatedProjetosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tarefas': {
      id: '/_authenticated/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof AuthenticatedTarefasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/de/': {
      id: '/de/'
      path: '/de'
      fullPath: '/de/'
      preLoaderRoute: typeof DeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de/contact': {
      id: '/de/contact'
      path: '/de/contact'
      fullPath: '/de/contact'
      preLoaderRoute: typeof DeContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de/portfolio': {
      id: '/de/portfolio'
      path: '/de/portfolio'
      fullPath: '/de/portfolio'
      preLoaderRoute: typeof DePortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de/restaurants': {
      id: '/de/restaurants'
      path: '/de/restaurants'
      fullPath: '/de/restaurants'
      preLoaderRoute: typeof DeRestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/contact': {
      id: '/en/contact'
      path: '/en/contact'
      fullPath: '/en/contact'
      preLoaderRoute: typeof EnContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/portfolio': {
      id: '/en/portfolio'
      path: '/en/portfolio'
      fullPath: '/en/portfolio'
      preLoaderRoute: typeof EnPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/restaurants': {
      id: '/en/restaurants'
      path: '/en/restaurants'
      fullPath: '/en/restaurants'
      preLoaderRoute: typeof EnRestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/': {
      id: '/es/'
      path: '/es'
      fullPath: '/es/'
      preLoaderRoute: typeof EsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/contact': {
      id: '/es/contact'
      path: '/es/contact'
      fullPath: '/es/contact'
      preLoaderRoute: typeof EsContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/portfolio': {
      id: '/es/portfolio'
      path: '/es/portfolio'
      fullPath: '/es/portfolio'
      preLoaderRoute: typeof EsPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/restaurantes': {
      id: '/es/restaurantes'
      path: '/es/restaurantes'
      fullPath: '/es/restaurantes'
      preLoaderRoute: typeof EsRestaurantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/': {
      id: '/fr/'
      path: '/fr'
      fullPath: '/fr/'
      preLoaderRoute: typeof FrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/contact': {
      id: '/fr/contact'
      path: '/fr/contact'
      fullPath: '/fr/contact'
      preLoaderRoute: typeof FrContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/portfolio': {
      id: '/fr/portfolio'
      path: '/fr/portfolio'
      fullPath: '/fr/portfolio'
      preLoaderRoute: typeof FrPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/restaurants': {
      id: '/fr/restaurants'
      path: '/fr/restaurants'
      fullPath: '/fr/restaurants'
      preLoaderRoute: typeof FrRestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurantes_/demonstracao': {
      id: '/restaurantes_/demonstracao'
      path: '/restaurantes/demonstracao'
      fullPath: '/restaurantes/demonstracao'
      preLoaderRoute: typeof RestaurantesDemonstracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/negocios/': {
      id: '/_authenticated/negocios/'
      path: '/negocios'
      fullPath: '/negocios/'
      preLoaderRoute: typeof AuthenticatedNegociosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/negocios/$id': {
      id: '/_authenticated/negocios/$id'
      path: '/negocios/$id'
      fullPath: '/negocios/$id'
      preLoaderRoute: typeof AuthenticatedNegociosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/de/restaurants_/demo': {
      id: '/de/restaurants_/demo'
      path: '/de/restaurants/demo'
      fullPath: '/de/restaurants/demo'
      preLoaderRoute: typeof DeRestaurantsDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/restaurants_/demo': {
      id: '/en/restaurants_/demo'
      path: '/en/restaurants/demo'
      fullPath: '/en/restaurants/demo'
      preLoaderRoute: typeof EnRestaurantsDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/restaurantes_/demo': {
      id: '/es/restaurantes_/demo'
      path: '/es/restaurantes/demo'
      fullPath: '/es/restaurantes/demo'
      preLoaderRoute: typeof EsRestaurantesDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/restaurants_/demo': {
      id: '/fr/restaurants_/demo'
      path: '/fr/restaurants/demo'
      fullPath: '/fr/restaurants/demo'
      preLoaderRoute: typeof FrRestaurantsDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedArquivosRoute: typeof AuthenticatedArquivosRoute
  AuthenticatedDefinicoesRoute: typeof AuthenticatedDefinicoesRoute
  AuthenticatedEmailsRoute: typeof AuthenticatedEmailsRoute
  AuthenticatedEquipaRoute: typeof AuthenticatedEquipaRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedPedidosRoute: typeof AuthenticatedPedidosRoute
  AuthenticatedPipelineRoute: typeof AuthenticatedPipelineRoute
  AuthenticatedProjetosRoute: typeof AuthenticatedProjetosRoute
  AuthenticatedTarefasRoute: typeof AuthenticatedTarefasRoute
  AuthenticatedNegociosIdRoute: typeof AuthenticatedNegociosIdRoute
  AuthenticatedNegociosIndexRoute: typeof AuthenticatedNegociosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedArquivosRoute: AuthenticatedArquivosRoute,
  AuthenticatedDefinicoesRoute: AuthenticatedDefinicoesRoute,
  AuthenticatedEmailsRoute: AuthenticatedEmailsRoute,
  AuthenticatedEquipaRoute: AuthenticatedEquipaRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedPedidosRoute: AuthenticatedPedidosRoute,
  AuthenticatedPipelineRoute: AuthenticatedPipelineRoute,
  AuthenticatedProjetosRoute: AuthenticatedProjetosRoute,
  AuthenticatedTarefasRoute: AuthenticatedTarefasRoute,
  AuthenticatedNegociosIdRoute: AuthenticatedNegociosIdRoute,
  AuthenticatedNegociosIndexRoute: AuthenticatedNegociosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactoRoute: ContactoRoute,
  PortefolioRoute: PortefolioRoute,
  RestaurantesRoute: RestaurantesRoute,
  DeContactRoute: DeContactRoute,
  DePortfolioRoute: DePortfolioRoute,
  DeRestaurantsRoute: DeRestaurantsRoute,
  EnContactRoute: EnContactRoute,
  EnPortfolioRoute: EnPortfolioRoute,
  EnRestaurantsRoute: EnRestaurantsRoute,
  EsContactRoute: EsContactRoute,
  EsPortfolioRoute: EsPortfolioRoute,
  EsRestaurantesRoute: EsRestaurantesRoute,
  FrContactRoute: FrContactRoute,
  FrPortfolioRoute: FrPortfolioRoute,
  FrRestaurantsRoute: FrRestaurantsRoute,
  RestaurantesDemonstracaoRoute: RestaurantesDemonstracaoRoute,
  DeIndexRoute: DeIndexRoute,
  EnIndexRoute: EnIndexRoute,
  EsIndexRoute: EsIndexRoute,
  FrIndexRoute: FrIndexRoute,
  DeRestaurantsDemoRoute: DeRestaurantsDemoRoute,
  EnRestaurantsDemoRoute: EnRestaurantsDemoRoute,
  EsRestaurantesDemoRoute: EsRestaurantesDemoRoute,
  FrRestaurantsDemoRoute: FrRestaurantsDemoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
